#ifndef _VIRTUAL_OS_HAL_EXTI_H
#define _VIRTUAL_OS_HAL_EXTI_H

#include "hal_gpio.h"

typedef enum {
	HAL_EXTI_LINE_0,
	HAL_EXTI_LINE_1,
	HAL_EXTI_LINE_2,
	HAL_EXTI_LINE_3,
	HAL_EXTI_LINE_4,
	HAL_EXTI_LINE_5,
	HAL_EXTI_LINE_6,
	HAL_EXTI_LINE_7,
	HAL_EXTI_LINE_8,
	HAL_EXTI_LINE_9,
	HAL_EXTI_LINE_10,
	HAL_EXTI_LINE_11,
	HAL_EXTI_LINE_12,
	HAL_EXTI_LINE_13,
	HAL_EXTI_LINE_14,
	HAL_EXTI_LINE_15,
	HAL_EXTI_LINE_16,
	HAL_EXTI_LINE_17,
	HAL_EXTI_LINE_18,
	HAL_EXTI_LINE_19,
	HAL_EXTI_LINE_20,
	HAL_EXTI_LINE_21,
	HAL_EXTI_LINE_22,
	HAL_EXTI_LINE_23,
	HAL_EXTI_LINE_24,
	HAL_EXTI_LINE_25,
	HAL_EXTI_LINE_26,
	HAL_EXTI_LINE_27,
	HAL_EXTI_LINE_28,
	HAL_EXTI_LINE_29,
} HAL_EXTI_LINE_E;

typedef enum {
	HAL_EXTI_MODE_INT,
	HAL_EXTI_MODE_EVE,
} HAL_EXTI_MODE_E;

typedef enum {
	HAL_EXTI_TRIG_RISING,
	HAL_EXTI_TRIG_FALLING,
	HAL_EXTI_TRIG_BOTH,
	HAL_EXTI_TRIG_NONE,
} HAL_EXTI_TRIG_TYPE_E;

typedef enum {
	HAL_EXTI_PORT_SOURCE_GPIOA,
	HAL_EXTI_PORT_SOURCE_GPIOB,
	HAL_EXTI_PORT_SOURCE_GPIOC,
	HAL_EXTI_PORT_SOURCE_GPIOD,
	HAL_EXTI_PORT_SOURCE_GPIOE,
	HAL_EXTI_PORT_SOURCE_GPIOF,
} HAL_EXTI_PORT_SOURCE_E;

typedef enum {
	HAL_EXTI_PIN_SOURCE_PIN0,
	HAL_EXTI_PIN_SOURCE_PIN1,
	HAL_EXTI_PIN_SOURCE_PIN2,
	HAL_EXTI_PIN_SOURCE_PIN3,
	HAL_EXTI_PIN_SOURCE_PIN4,
	HAL_EXTI_PIN_SOURCE_PIN5,
	HAL_EXTI_PIN_SOURCE_PIN6,
	HAL_EXTI_PIN_SOURCE_PIN7,
	HAL_EXTI_PIN_SOURCE_PIN8,
	HAL_EXTI_PIN_SOURCE_PIN9,
	HAL_EXTI_PIN_SOURCE_PIN10,
	HAL_EXTI_PIN_SOURCE_PIN11,
	HAL_EXTI_PIN_SOURCE_PIN12,
	HAL_EXTI_PIN_SOURCE_PIN13,
	HAL_EXTI_PIN_SOURCE_PIN14,
	HAL_EXTI_PIN_SOURCE_PIN15,
} HAL_EXTI_PIN_SOURCE_E;

typedef struct {
	HAL_EXTI_LINE_E HAL_EXTI_LINE;
	HAL_EXTI_MODE_E HAL_EXTI_MODE;
	HAL_EXTI_TRIG_TYPE_E HAL_EXTI_TRIG_TYPE;

	HAL_EXTI_PORT_SOURCE_E HAL_EXTI_PORT_SOURCE;
	HAL_EXTI_PIN_SOURCE_E HAL_EXTI_PIN_SOURCE;
} HAL_EXTI_CFG_T;

typedef enum {
	HAL_NVIC_PRIORITY_HIGHEST,
	HAL_NVIC_PRIORITY_HIGH,
	HAL_NVIC_PRIORITY_MID,
	HAL_NVIC_PRIORITY_LOW,
} HAL_NVIC_PRIORITY_E;

void hal_exti_deinit(void);
void hal_exti_init(HAL_EXTI_CFG_T *exti_cfg);

/**
 * @brief NVIC使能
 * @param irqn          查数据手�?
 * @param priority      0~3
*/
void hal_nvic_irq_enable(uint8_t irqn, uint8_t priority);
void hal_nvic_irq_disable(uint8_t irqn);

void hal_exti_enable(HAL_EXTI_LINE_E exit_line);
void hal_exti_disable(HAL_EXTI_LINE_E exit_line);

#endif
